# English translations for Open-Capture For Invoices
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2022-03-18 10:18+0100\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: en\n"
"Language-Team: en <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.1\n"

#: src/backend/classes/MaarchWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr "Host not found"

#: src/backend/controllers/accounts.py:47 src/backend/models/accounts.py:51
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Error retrieving supplier"

#: src/backend/controllers/accounts.py:60 src/backend/models/accounts.py:70
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Error retrieving address"

#: src/backend/controllers/accounts.py:80
#: src/backend/controllers/accounts.py:86
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Error updating supplier"

#: src/backend/controllers/accounts.py:112
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Error updating supplier positions"

#: src/backend/controllers/accounts.py:137
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Error update supplier pages"

#: src/backend/controllers/accounts.py:163
#: src/backend/controllers/accounts.py:169
#: src/backend/controllers/accounts.py:195
#: src/backend/controllers/accounts.py:201 src/backend/models/accounts.py:108
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Error updating address"

#: src/backend/controllers/accounts.py:228 src/backend/models/accounts.py:124
msgid "CREATE_ADDRESS_ERROR"
msgstr "Error creating address"

#: src/backend/controllers/accounts.py:262
#: src/backend/controllers/accounts.py:268 src/backend/models/accounts.py:140
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Error creating supplier"

#: src/backend/controllers/accounts.py:269
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A supplier already exists with this vat number"

#: src/backend/controllers/accounts.py:292 src/backend/controllers/user.py:86
#: src/backend/models/accounts.py:192 src/backend/models/accounts.py:211
#: src/backend/models/accounts.py:226 src/backend/models/user.py:132
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Error retrieving customer"

#: src/backend/controllers/accounts.py:334
#: src/backend/controllers/accounts.py:340 src/backend/models/accounts.py:244
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Error updating customer"

#: src/backend/controllers/accounts.py:371
#: src/backend/controllers/accounts.py:377 src/backend/models/accounts.py:260
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Error creating customer"

#: src/backend/controllers/accounts.py:378
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A customer already exists with this vat number"

#: src/backend/controllers/accounts.py:394
#: src/backend/controllers/accounts.py:400 src/backend/models/accounts.py:278
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Error deleting customer"

#: src/backend/controllers/accounts.py:417
#: src/backend/controllers/accounts.py:423 src/backend/models/accounts.py:158
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Error deleting supplier"

#: src/backend/controllers/accounts.py:441
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Error while loading supplier referencial"

#: src/backend/controllers/auth.py:80
msgid "LOGIN_ERROR"
msgstr "Login error"

#: src/backend/controllers/auth.py:95 src/backend/controllers/auth.py:103
#: src/backend/controllers/auth.py:105
msgid "JWT_ERROR"
msgstr "Authentification by token error"

#: src/backend/controllers/doctypes.py:131
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/doctypes.py:134
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:137
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/forms.py:66 src/backend/controllers/forms.py:115
#: src/backend/models/forms.py:52
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Error retrieving form"

#: src/backend/controllers/forms.py:98
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Error retrieving form fields"

#: src/backend/controllers/forms.py:162 src/backend/controllers/forms.py:168
msgid "DELETE_FORM_ERROR"
msgstr "Error deleting form"

#: src/backend/controllers/forms.py:184
#: src/backend/controllers/positions_masks.py:154
msgid "COPY_OF"
msgstr "Copy of"

#: src/backend/controllers/forms.py:200 src/backend/controllers/forms.py:206
msgid "DUPLICATE_FORM_ERROR"
msgstr "Error duplicating form"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:229
msgid "DISABLE_FORM_ERROR"
msgstr "Error disabling form"

#: src/backend/controllers/forms.py:246 src/backend/controllers/forms.py:252
msgid "ENABLE_FORM_ERROR"
msgstr "Error enabling form"

#: src/backend/controllers/forms.py:285 src/backend/controllers/forms.py:291
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Error updating form fields"

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr "Error while adding new history"

#: src/backend/controllers/inputs.py:52 src/backend/controllers/inputs.py:58
msgid "UPDATE_INPUT_ERROR"
msgstr "Error while updating input"

#: src/backend/controllers/inputs.py:85 src/backend/controllers/inputs.py:96
#: src/backend/controllers/inputs.py:109
msgid "CREATE_INPUT_ERROR"
msgstr "Error while creating input"

#: src/backend/controllers/inputs.py:86
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr "The label short already exists"

#: src/backend/controllers/inputs.py:97
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "The document capture path is already set in another input"

#: src/backend/controllers/inputs.py:122
msgid "GET_INPUT_BY_ID_ERROR"
msgstr "Error while retrieving input"

#: src/backend/controllers/inputs.py:146 src/backend/controllers/inputs.py:152
msgid "DELETE_INPUT_ERROR"
msgstr "Error while deleting input"

#: src/backend/controllers/inputs.py:181
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Error while deleting fs watcher settings"

#: src/backend/controllers/inputs.py:182 src/backend/controllers/inputs.py:241
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "Fs watcher config doesnt exists"

#: src/backend/controllers/inputs.py:222 src/backend/controllers/inputs.py:240
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Error while creating fs watcher settings"

#: src/backend/controllers/inputs.py:223
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/inputs.py:246
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Script sample doesn't exists"

#: src/backend/controllers/inputs.py:252
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Script folder doesn't exists"

#: src/backend/controllers/outputs.py:72 src/backend/controllers/outputs.py:78
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Error while updating output"

#: src/backend/controllers/outputs.py:104
msgid "CREATE_OUTPUT_ERROR"
msgstr "Error while creating output"

#: src/backend/controllers/outputs.py:117
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/outputs.py:130
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Error while retrieving output type"

#: src/backend/controllers/outputs.py:147
#: src/backend/controllers/outputs.py:153
msgid "DELETE_OUTPUT_ERROR"
msgstr "Error while deleting output"

#: src/backend/controllers/positions_masks.py:75
#: src/backend/controllers/positions_masks.py:92
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/controllers/positions_masks.py:137
#: src/backend/controllers/positions_masks.py:143
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Error while deleting positions mask"

#: src/backend/controllers/positions_masks.py:170
#: src/backend/controllers/positions_masks.py:176
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Error while duplicating positions mask"

#: src/backend/controllers/positions_masks.py:193
#: src/backend/controllers/positions_masks.py:199
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Error while disabling positions mask"

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Error while enabling positions mask"

#: src/backend/controllers/positions_masks.py:247
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updating positions mask positions"

#: src/backend/controllers/positions_masks.py:272
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updateing positions mask pages"

#: src/backend/controllers/positions_masks.py:292
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask positions"

#: src/backend/controllers/positions_masks.py:312
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask pages"

#: src/backend/controllers/privileges.py:36
#: src/backend/controllers/privileges.py:64
msgid "GET_PRIVILEGES_ERROR"
msgstr "Error while retrieving privileges"

#: src/backend/controllers/roles.py:53 src/backend/controllers/roles.py:59
#: src/backend/controllers/roles.py:106 src/backend/controllers/roles.py:112
#: src/backend/models/roles.py:70
msgid "UPDATE_ROLE_ERROR"
msgstr "Error while trying to update role"

#: src/backend/controllers/roles.py:84 src/backend/models/roles.py:86
msgid "CREATE_ROLE_ERROR"
msgstr "Error while creating role"

#: src/backend/controllers/roles.py:125
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Error while retrieving role"

#: src/backend/controllers/roles.py:142 src/backend/controllers/roles.py:148
msgid "DELETE_ROLE_ERROR"
msgstr "Error while deleting role"

#: src/backend/controllers/roles.py:165 src/backend/controllers/roles.py:171
msgid "DISABLE_ROLE_ERROR"
msgstr "Error while disabling role"

#: src/backend/controllers/roles.py:188 src/backend/controllers/roles.py:194
msgid "ENABLE_ROLE_ERROR"
msgstr "Error while enabling role"

#: src/backend/controllers/splitter.py:68
#: src/backend/controllers/verifier.py:75
msgid "AT"
msgstr "at"

#: src/backend/controllers/splitter.py:178
#: src/backend/controllers/splitter.py:329
msgid "ADD_DOCUMENT_ERROR"
msgstr "Error while adding document"

#: src/backend/controllers/splitter.py:229
#: src/backend/controllers/splitter.py:235
#: src/backend/controllers/verifier.py:439
#: src/backend/controllers/verifier.py:445
#: src/backend/controllers/verifier.py:451
msgid "EXPORT_MAARCH_ERROR"
msgstr "Error during Maarch export"

#: src/backend/controllers/splitter.py:241
#: src/backend/controllers/verifier.py:463
msgid "MAARCH_WS_INFO_EMPTY"
msgstr "Maarch informations are empty"

#: src/backend/controllers/splitter.py:267
msgid "EXPORT_PDF_ERROR"
msgstr "Error while exporting PDF"

#: src/backend/controllers/splitter.py:284
#: src/backend/controllers/splitter.py:493
#: src/backend/controllers/splitter.py:512
#: src/backend/controllers/verifier.py:555
msgid "EXPORT_XML_ERROR"
msgstr "Error while exporting XML"

#: src/backend/controllers/splitter.py:304
msgid "UPDATE_BATCH_ERROR"
msgstr "Error while updating batch"

#: src/backend/controllers/splitter.py:345
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:365
#: src/backend/controllers/splitter.py:380
#: src/backend/controllers/splitter.py:394
msgid "UPDATE_PAGES_ERROR"
msgstr "Error while updating pages"

#: src/backend/controllers/splitter.py:407
msgid "CMIS_CONNECTION_ERROR"
msgstr "Errur while connecting to CMIS"

#: src/backend/controllers/splitter.py:573
#: src/backend/controllers/verifier.py:703 src/backend/models/splitter.py:442
#: src/backend/models/verifier.py:134
msgid "GET_TOTALS_ERROR"
msgstr "Error while retrievings totals"

#: src/backend/controllers/status.py:35
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Error while retrieving status"

#: src/backend/controllers/user.py:31
msgid "CREATE_USER_ERROR"
msgstr "Error while creating user"

#: src/backend/controllers/user.py:69 src/backend/models/user.py:113
msgid "GET_USER_BY_ID_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:100
msgid "UPDATE_PROFILE"
msgstr "Update profile"

#: src/backend/controllers/user.py:101
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "The old password do not match"

#: src/backend/controllers/user.py:124 src/backend/controllers/user.py:130
#: src/backend/models/user.py:151
msgid "UPDATE_USER_ERROR"
msgstr "Error while updating user"

#: src/backend/controllers/user.py:147 src/backend/controllers/user.py:153
msgid "DELETE_USER_ERROR"
msgstr "Error while deleting user"

#: src/backend/controllers/user.py:170 src/backend/controllers/user.py:176
msgid "DISABLE_USER_ERROR"
msgstr "Error while disabling user"

#: src/backend/controllers/user.py:193 src/backend/controllers/user.py:199
msgid "ENABLE_USER_ERROR"
msgstr "Error while enabling user"

#: src/backend/controllers/user.py:219 src/backend/controllers/user.py:225
#: src/backend/models/user.py:169
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Error while updating user customers"

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:34
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr "Error while retrieving invoice"

#: src/backend/controllers/verifier.py:163
#: src/backend/controllers/verifier.py:253
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr "Error while updating invoice positions"

#: src/backend/controllers/verifier.py:188
#: src/backend/controllers/verifier.py:273
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr "Error while updating invoice pages"

#: src/backend/controllers/verifier.py:212
#: src/backend/controllers/verifier.py:232
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr "Error while updating invoice datas"

#: src/backend/controllers/verifier.py:290
#: src/backend/controllers/verifier.py:296
msgid "DELETE_INVOICE_ERROR"
msgstr "Error while deleting invoice"

#: src/backend/controllers/verifier.py:314
#: src/backend/controllers/verifier.py:320
msgid "UPDATE_INVOICE_ERROR"
msgstr "Error while updating invoice"

#: src/backend/controllers/verifier.py:340
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Error while removing lock on invoice"

#: src/backend/controllers/verifier.py:446
msgid "PDF_FILE_NOT_FOUND"
msgstr "PDF file not found"

#: src/backend/controllers/verifier.py:457
msgid "MAARCH_WS_INFO_WRONG"
msgstr "Maarch informations are wrong"

#: src/backend/controllers/verifier.py:549
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for XML doesn't exists"

#: src/backend/controllers/verifier.py:631
#: src/backend/controllers/verifier.py:634
#: src/backend/controllers/verifier.py:647
#: src/backend/controllers/verifier.py:664
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Error while connecting to INSEE API"

#: src/backend/controllers/verifier.py:686
msgid "VAT_NOT_VALID"
msgstr "VAT number not valid"

#: src/backend/controllers/verifier.py:690
msgid "VAT_API_ERROR"
msgstr "API for VAT number unreachable"

#: src/backend/models/accounts.py:90
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Error while updating supplier"

#: src/backend/models/auth.py:35 src/backend/models/user.py:37
msgid "BAD_USERNAME"
msgstr "Bad username"

#: src/backend/models/auth.py:37 src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr "Bad password"

#: src/backend/models/auth.py:39
msgid "USER_DELETED"
msgstr "User deleted"

#: src/backend/models/auth.py:41
msgid "USER_DISABLED"
msgstr "User disabled"

#: src/backend/models/config.py:100
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Error while updating configuration"

#: src/backend/models/config.py:122
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Error while updating docserver"

#: src/backend/models/custom_fields.py:45
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Error while creating custom field"

#: src/backend/models/custom_fields.py:48
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Custom field already exist"

#: src/backend/models/custom_fields.py:87
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Error while updating custom fields"

#: src/backend/models/custom_fields.py:107
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/models/doctypes.py:45
msgid "ADD_DOCTYPE_ERROR"
msgstr "Error while adding doctype"

#: src/backend/models/doctypes.py:48
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Un type de document existe "

#: src/backend/models/doctypes.py:85
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Error lors de l'édition du type de document"

#: src/backend/models/doctypes.py:112 src/backend/models/doctypes.py:115
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Error while updating default doctype"

#: src/backend/models/forms.py:71
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Error while retrieving default form"

#: src/backend/models/forms.py:91
msgid "UPDATE_FORM_ERROR"
msgstr "Error while updating form"

#: src/backend/models/forms.py:109
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Error while updating form fields"

#: src/backend/models/forms.py:149
msgid "ADD_FORM_ERROR"
msgstr "Error while creating form"

#: src/backend/models/forms.py:152
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Form label already exist"

#: src/backend/models/inputs.py:50
msgid "INPUT_DOESNT_EXISTS"
msgstr "Input doesn't exists"

#: src/backend/models/inputs.py:84
msgid "INPUT_UPDATE_ERROR"
msgstr "Error while updating input"

#: src/backend/models/inputs.py:100
msgid "INPUT_CREATE_ERROR"
msgstr "Error while creating input"

#: src/backend/models/outputs.py:64
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "Output doesn't exists"

#: src/backend/models/outputs.py:83
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Output type doesn't exists"

#: src/backend/models/outputs.py:103
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Error while updating output"

#: src/backend/models/outputs.py:119
msgid "OUTPUT_CREATE_ERROR"
msgstr "Error while creating output"

#: src/backend/models/positions_masks.py:52
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/models/positions_masks.py:72
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Error while updating positions mask"

#: src/backend/models/positions_masks.py:90
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Error while updating positions mask fields"

#: src/backend/models/positions_masks.py:120
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Error while creating positions mask"

#: src/backend/models/positions_masks.py:123
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Positions mask label already exists"

#: src/backend/models/privileges.py:32 src/backend/models/privileges.py:49
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Error while retrieving privileges"

#: src/backend/models/roles.py:50
msgid "ROLE_DOESNT_EXISTS"
msgstr "Role doesn't exists"

#: src/backend/models/roles.py:104
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Error while updating role privileges"

#: src/backend/models/roles.py:122
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Error while creating role privileges"

#: src/backend/models/splitter.py:70
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter index"

#: src/backend/models/splitter.py:110
msgid "GET_DEMAND_NUMBER_ERROR"
msgstr "Error while getting splitter demand number"

#: src/backend/models/splitter.py:129
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Error while updating splitter settings"

#: src/backend/models/splitter.py:150
msgid "INSERT_REFERENTIAL_ERROR"
msgstr "Error while inserting splitter referential"

#: src/backend/models/splitter.py:171
msgid "INSERT_PAGE_ERROR"
msgstr "Error while inserting splitter pages"

#: src/backend/models/splitter.py:229
msgid "GET_BATCH_ERROR"
msgstr "Error while getting splitter batches"

#: src/backend/models/splitter.py:248
msgid "GET_DOCUMENTS_ERROR"
msgstr "Error while getting splitter documents"

#: src/backend/models/splitter.py:267
msgid "GET_PAGES_ERROR"
msgstr "Error while getting splitter pages"

#: src/backend/models/splitter.py:285
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Error while getting splitter source pages value"

#: src/backend/models/splitter.py:322
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter maximum index"

#: src/backend/models/status.py:34
msgid "NO_STATUS"
msgstr "No status"

#: src/backend/models/user.py:41
msgid "USER"
msgstr "User"

#: src/backend/models/user.py:41
msgid "ALREADY_REGISTERED"
msgstr "Already registered"

#: src/backend/models/verifier.py:86 src/backend/models/verifier.py:103
msgid "INVOICE_UPDATE_ERROR"
msgstr "Error while updating invoice"

#: src/backend/rest/auth.py:36
msgid "PGSQL_ERROR"
msgstr "Error while connecting to database"

#: src/backend/rest/splitter.py:39 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr "Unknow error"

#~ msgid "ADD_DOC_TYPE_ERROR"
#~ msgstr "Error lors de l'ajout du type de document"

#~ msgid "CHANGE_LOCALE_ERROR"
#~ msgstr "Error while changing locale"

#~ msgid "INPUT_FOLDER_DOESNT_EXISTS_OR_NOT_WRITEABLE"
#~ msgstr "Input folder doesnt exists or it's not writeable"

