# English translations for Open-Capture For Invoices
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2021-12-24 16:32+0100\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: en\n"
"Language-Team: en <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.1\n"

#: src/backend/classes/MaarchWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr "Host not found"

#: src/backend/controllers/accounts.py:47 src/backend/models/accounts.py:51
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Error retrieving supplier"

#: src/backend/controllers/accounts.py:60 src/backend/models/accounts.py:70
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Error retrieving address"

#: src/backend/controllers/accounts.py:80
#: src/backend/controllers/accounts.py:86
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Error updating supplier"

#: src/backend/controllers/accounts.py:112
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Error updating supplier positions"

#: src/backend/controllers/accounts.py:137
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Error update supplier pages"

#: src/backend/controllers/accounts.py:163
#: src/backend/controllers/accounts.py:169
#: src/backend/controllers/accounts.py:195
#: src/backend/controllers/accounts.py:201 src/backend/models/accounts.py:108
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Error updating address"

#: src/backend/controllers/accounts.py:228 src/backend/models/accounts.py:124
msgid "CREATE_ADDRESS_ERROR"
msgstr "Error creating address"

#: src/backend/controllers/accounts.py:262
#: src/backend/controllers/accounts.py:268 src/backend/models/accounts.py:140
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Error creating supplier"

#: src/backend/controllers/accounts.py:269
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A supplier already exists with this vat number"

#: src/backend/controllers/accounts.py:292 src/backend/controllers/user.py:86
#: src/backend/models/accounts.py:192 src/backend/models/accounts.py:211
#: src/backend/models/accounts.py:226 src/backend/models/user.py:132
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Error retrieving customer"

#: src/backend/controllers/accounts.py:334
#: src/backend/controllers/accounts.py:340 src/backend/models/accounts.py:244
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Error updating customer"

#: src/backend/controllers/accounts.py:371
#: src/backend/controllers/accounts.py:377 src/backend/models/accounts.py:260
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Error creating customer"

#: src/backend/controllers/accounts.py:378
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A customer already exists with this vat number"

#: src/backend/controllers/accounts.py:394
#: src/backend/controllers/accounts.py:400 src/backend/models/accounts.py:278
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Error deleting customer"

#: src/backend/controllers/accounts.py:417
#: src/backend/controllers/accounts.py:423 src/backend/models/accounts.py:158
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Error deleting supplier"

#: src/backend/controllers/accounts.py:440
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Error while loading supplier referencial"

#: src/backend/controllers/auth.py:80
msgid "LOGIN_ERROR"
msgstr "Login error"

#: src/backend/controllers/auth.py:95 src/backend/controllers/auth.py:103
#: src/backend/controllers/auth.py:105
msgid "JWT_ERROR"
msgstr "Authentification by token error"

#: src/backend/controllers/config.py:46
msgid "CHANGE_LOCALE_ERROR"
msgstr "Error while changing locale"

#: src/backend/controllers/forms.py:66 src/backend/controllers/forms.py:115
#: src/backend/models/forms.py:52
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Error retrieving form"

#: src/backend/controllers/forms.py:98
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Error retrieving form fields"

#: src/backend/controllers/forms.py:162 src/backend/controllers/forms.py:168
msgid "DELETE_FORM_ERROR"
msgstr "Error deleting form"

#: src/backend/controllers/forms.py:184
#: src/backend/controllers/positions_masks.py:154
msgid "COPY_OF"
msgstr "Copy of"

#: src/backend/controllers/forms.py:200 src/backend/controllers/forms.py:206
msgid "DUPLICATE_FORM_ERROR"
msgstr "Error duplicating form"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:229
msgid "DISABLE_FORM_ERROR"
msgstr "Error disabling form"

#: src/backend/controllers/forms.py:246 src/backend/controllers/forms.py:252
msgid "ENABLE_FORM_ERROR"
msgstr "Error enabling form"

#: src/backend/controllers/forms.py:285 src/backend/controllers/forms.py:291
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Error updating form fields"

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr "Error while adding new history"

#: src/backend/controllers/inputs.py:50 src/backend/controllers/inputs.py:56
msgid "UPDATE_INPUT_ERROR"
msgstr "Error while updating input"

#: src/backend/controllers/inputs.py:81 src/backend/controllers/inputs.py:92
#: src/backend/controllers/inputs.py:105
msgid "CREATE_INPUT_ERROR"
msgstr "Error while creating input"

#: src/backend/controllers/inputs.py:82
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr "The label short already exists"

#: src/backend/controllers/inputs.py:93
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "The document capture path is already set in another input"

#: src/backend/controllers/inputs.py:118
msgid "GET_INPUT_BY_ID_ERROR"
msgstr "Error while retrieving input"

#: src/backend/controllers/inputs.py:142 src/backend/controllers/inputs.py:148
msgid "DELETE_INPUT_ERROR"
msgstr "Error while deleting input"

#: src/backend/controllers/inputs.py:176
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Error while deleting fs watcher settings"

#: src/backend/controllers/inputs.py:177 src/backend/controllers/inputs.py:231
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "Fs watcher config doesnt exists"

#: src/backend/controllers/inputs.py:212 src/backend/controllers/inputs.py:230
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Error while creating fs watcher settings"

#: src/backend/controllers/inputs.py:213
msgid "INPUT_FOLDER_DOESNT_EXISTS_OR_NOT_WRITEABLE"
msgstr "Input folder doesnt exists or it's not writeable"

#: src/backend/controllers/inputs.py:236
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Script sample doesn't exists"

#: src/backend/controllers/inputs.py:242
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Script folder doesn't exists"

#: src/backend/controllers/outputs.py:71 src/backend/controllers/outputs.py:77
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Error while updating output"

#: src/backend/controllers/outputs.py:102
msgid "CREATE_OUTPUT_ERROR"
msgstr "Error while creating output"

#: src/backend/controllers/outputs.py:115
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/outputs.py:128
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Error while retrieving output type"

#: src/backend/controllers/outputs.py:145
#: src/backend/controllers/outputs.py:151
msgid "DELETE_OUTPUT_ERROR"
msgstr "Error while deleting output"

#: src/backend/controllers/positions_masks.py:75
#: src/backend/controllers/positions_masks.py:92
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/controllers/positions_masks.py:137
#: src/backend/controllers/positions_masks.py:143
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Error while deleting positions mask"

#: src/backend/controllers/positions_masks.py:170
#: src/backend/controllers/positions_masks.py:176
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Error while duplicating positions mask"

#: src/backend/controllers/positions_masks.py:193
#: src/backend/controllers/positions_masks.py:199
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Error while disabling positions mask"

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Error while enabling positions mask"

#: src/backend/controllers/positions_masks.py:247
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updating positions mask positions"

#: src/backend/controllers/positions_masks.py:272
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updateing positions mask pages"

#: src/backend/controllers/positions_masks.py:292
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask positions"

#: src/backend/controllers/positions_masks.py:312
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask pages"

#: src/backend/controllers/privileges.py:36
#: src/backend/controllers/privileges.py:64
msgid "GET_PRIVILEGES_ERROR"
msgstr "Error while retrieving privileges"

#: src/backend/controllers/roles.py:53 src/backend/controllers/roles.py:59
#: src/backend/controllers/roles.py:106 src/backend/controllers/roles.py:112
#: src/backend/models/roles.py:70
msgid "UPDATE_ROLE_ERROR"
msgstr "Error while trying to update role"

#: src/backend/controllers/roles.py:84 src/backend/models/roles.py:86
msgid "CREATE_ROLE_ERROR"
msgstr "Error while creating role"

#: src/backend/controllers/roles.py:125
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Error while retrieving role"

#: src/backend/controllers/roles.py:142 src/backend/controllers/roles.py:148
msgid "DELETE_ROLE_ERROR"
msgstr "Error while deleting role"

#: src/backend/controllers/roles.py:165 src/backend/controllers/roles.py:171
msgid "DISABLE_ROLE_ERROR"
msgstr "Error while disabling role"

#: src/backend/controllers/roles.py:188 src/backend/controllers/roles.py:194
msgid "ENABLE_ROLE_ERROR"
msgstr "Error while enabling role"

#: src/backend/controllers/splitter.py:61
#: src/backend/controllers/verifier.py:73
msgid "AT"
msgstr "at"

#: src/backend/controllers/status.py:35
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Error while retrieving status"

#: src/backend/controllers/user.py:31
msgid "CREATE_USER_ERROR"
msgstr "Error while creating user"

#: src/backend/controllers/user.py:69 src/backend/models/user.py:113
msgid "GET_USER_BY_ID_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:100
msgid "UPDATE_PROFILE"
msgstr "Update profile"

#: src/backend/controllers/user.py:101
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "The old password do not match"

#: src/backend/controllers/user.py:124 src/backend/controllers/user.py:130
#: src/backend/models/user.py:151
msgid "UPDATE_USER_ERROR"
msgstr "Error while updating user"

#: src/backend/controllers/user.py:147 src/backend/controllers/user.py:153
msgid "DELETE_USER_ERROR"
msgstr "Error while deleting user"

#: src/backend/controllers/user.py:170 src/backend/controllers/user.py:176
msgid "DISABLE_USER_ERROR"
msgstr "Error while disabling user"

#: src/backend/controllers/user.py:193 src/backend/controllers/user.py:199
msgid "ENABLE_USER_ERROR"
msgstr "Error while enabling user"

#: src/backend/controllers/user.py:219 src/backend/controllers/user.py:225
#: src/backend/models/user.py:169
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Error while updating user customers"

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:34
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr "Error while retrieving invoice"

#: src/backend/controllers/verifier.py:161
#: src/backend/controllers/verifier.py:251
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr "Error while updating invoice positions"

#: src/backend/controllers/verifier.py:186
#: src/backend/controllers/verifier.py:271
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr "Error while updating invoice pages"

#: src/backend/controllers/verifier.py:210
#: src/backend/controllers/verifier.py:230
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr "Error while updating invoice datas"

#: src/backend/controllers/verifier.py:288
#: src/backend/controllers/verifier.py:294
msgid "DELETE_INVOICE_ERROR"
msgstr "Error while deleting invoice"

#: src/backend/controllers/verifier.py:312
#: src/backend/controllers/verifier.py:318
msgid "UPDATE_INVOICE_ERROR"
msgstr "Error while updating invoice"

#: src/backend/controllers/verifier.py:338
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Error while removing lock on invoice"

#: src/backend/controllers/verifier.py:437
#: src/backend/controllers/verifier.py:443
#: src/backend/controllers/verifier.py:449
msgid "EXPORT_MAARCH_ERROR"
msgstr "Error during Maarch export"

#: src/backend/controllers/verifier.py:444
msgid "PDF_FILE_NOT_FOUND"
msgstr "PDF file not found"

#: src/backend/controllers/verifier.py:455
msgid "MAARCH_WS_INFO_WRONG"
msgstr "Maarch informations are wrong"

#: src/backend/controllers/verifier.py:461
msgid "MAARCH_WS_INFO_EMPTY"
msgstr "Maarch informations are empty"

#: src/backend/controllers/verifier.py:547
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for XML doesn't exists"

#: src/backend/controllers/verifier.py:553
msgid "EXPORT_XML_ERROR"
msgstr "Error while exporting XML"

#: src/backend/controllers/verifier.py:617
#: src/backend/controllers/verifier.py:620
#: src/backend/controllers/verifier.py:633
#: src/backend/controllers/verifier.py:650
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Error while connecting to INSEE API"

#: src/backend/controllers/verifier.py:672
msgid "VAT_NOT_VALID"
msgstr "VAT number not valid"

#: src/backend/controllers/verifier.py:676
msgid "VAT_API_ERROR"
msgstr "API for VAT number unreachable"

#: src/backend/models/accounts.py:90
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Error while updating supplier"

#: src/backend/models/auth.py:35 src/backend/models/user.py:37
msgid "BAD_USERNAME"
msgstr "Bad username"

#: src/backend/models/auth.py:37 src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr "Bad password"

#: src/backend/models/auth.py:39
msgid "USER_DELETED"
msgstr "User deleted"

#: src/backend/models/auth.py:41
msgid "USER_DISABLED"
msgstr "User disabled"

#: src/backend/models/custom_fields.py:45
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Error while creating custom field"

#: src/backend/models/custom_fields.py:48
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Custom field already exist"

#: src/backend/models/custom_fields.py:86
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Error while updating custom fields"

#: src/backend/models/forms.py:71
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Error while retrieving default form"

#: src/backend/models/forms.py:91
msgid "UPDATE_FORM_ERROR"
msgstr "Error while updating form"

#: src/backend/models/forms.py:109
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Error while updating form fields"

#: src/backend/models/forms.py:149
msgid "ADD_FORM_ERROR"
msgstr "Error while creating form"

#: src/backend/models/forms.py:152
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Form label already exist"

#: src/backend/models/inputs.py:50
msgid "INPUT_DOESNT_EXISTS"
msgstr "Input doesn't exists"

#: src/backend/models/inputs.py:84
msgid "INPUT_UPDATE_ERROR"
msgstr "Error while updating input"

#: src/backend/models/inputs.py:100
msgid "INPUT_CREATE_ERROR"
msgstr "Error while creating input"

#: src/backend/models/outputs.py:64
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "Output doesn't exists"

#: src/backend/models/outputs.py:83
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Output type doesn't exists"

#: src/backend/models/outputs.py:103
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Error while updating output"

#: src/backend/models/outputs.py:119
msgid "OUTPUT_CREATE_ERROR"
msgstr "Error while creating output"

#: src/backend/models/positions_masks.py:52
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/models/positions_masks.py:72
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Error while updating positions mask"

#: src/backend/models/positions_masks.py:90
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Error while updating positions mask fields"

#: src/backend/models/positions_masks.py:120
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Error while creating positions mask"

#: src/backend/models/positions_masks.py:123
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Positions mask label already exists"

#: src/backend/models/privileges.py:32 src/backend/models/privileges.py:49
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Error while retrieving privileges"

#: src/backend/models/roles.py:50
msgid "ROLE_DOESNT_EXISTS"
msgstr "Role doesn't exists"

#: src/backend/models/roles.py:104
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Error while updating role privileges"

#: src/backend/models/roles.py:122
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Error while creating role privileges"

#: src/backend/models/status.py:34
msgid "NO_STATUS"
msgstr "No status"

#: src/backend/models/user.py:41
msgid "USER"
msgstr "User"

#: src/backend/models/user.py:41
msgid "ALREADY_REGISTERED"
msgstr "Already registered"

#: src/backend/models/verifier.py:86 src/backend/models/verifier.py:103
msgid "INVOICE_UPDATE_ERROR"
msgstr "Error while updating invoice"

#: src/backend/rest/auth.py:44
msgid "PGSQL_ERROR"
msgstr "Error while connecting to database"

#: src/backend/rest/splitter.py:39 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr "Unknow error"
