# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-07-05 14:45+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.1\n"

#: src/backend/classes/MaarchWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr ""

#: src/backend/controllers/accounts.py:47 src/backend/models/accounts.py:51
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:60 src/backend/models/accounts.py:70
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:80
#: src/backend/controllers/accounts.py:86
msgid "UPDATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:112
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:137
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:163
#: src/backend/controllers/accounts.py:169
#: src/backend/controllers/accounts.py:195
#: src/backend/controllers/accounts.py:201 src/backend/models/accounts.py:108
msgid "UPDATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:228 src/backend/models/accounts.py:124
msgid "CREATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:264
#: src/backend/controllers/accounts.py:270 src/backend/models/accounts.py:140
msgid "CREATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:271
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:294 src/backend/controllers/user.py:116
#: src/backend/models/accounts.py:192 src/backend/models/accounts.py:211
#: src/backend/models/accounts.py:226 src/backend/models/user.py:154
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:336
#: src/backend/controllers/accounts.py:342 src/backend/models/accounts.py:244
msgid "UPDATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:373
#: src/backend/controllers/accounts.py:379 src/backend/models/accounts.py:260
msgid "CREATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:380
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:396
#: src/backend/controllers/accounts.py:402 src/backend/models/accounts.py:278
msgid "DELETE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:419
#: src/backend/controllers/accounts.py:425 src/backend/models/accounts.py:158
msgid "DELETE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:443
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:86 src/backend/controllers/auth.py:130
#: src/backend/rest/auth.py:90 src/backend/rest/auth.py:202
#: src/backend/rest/auth.py:207
msgid "LOGIN_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:101 src/backend/controllers/auth.py:109
#: src/backend/controllers/auth.py:111
msgid "JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:186
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:198
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:210
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:131
msgid "DOCTYPESEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:134
msgid "DOCUMENTSEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:137
msgid "BUNDLESEPARATOR"
msgstr ""

#: src/backend/controllers/forms.py:73 src/backend/controllers/forms.py:122
#: src/backend/models/forms.py:52
msgid "GET_FORM_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:105
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:169 src/backend/controllers/forms.py:175
msgid "DELETE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:187 src/backend/controllers/inputs.py:70
#: src/backend/controllers/outputs.py:64
#: src/backend/controllers/positions_masks.py:154
msgid "COPY_OF"
msgstr ""

#: src/backend/controllers/forms.py:204 src/backend/controllers/forms.py:210
msgid "DUPLICATE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:227 src/backend/controllers/forms.py:233
msgid "DISABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:250 src/backend/controllers/forms.py:256
msgid "ENABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:289 src/backend/controllers/forms.py:295
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:49 src/backend/controllers/inputs.py:55
msgid "UPDATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:83 src/backend/controllers/inputs.py:89
msgid "DUPLICATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:116 src/backend/controllers/inputs.py:127
#: src/backend/controllers/inputs.py:140
msgid "CREATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:117
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:128
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:153
msgid "GET_INPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:177 src/backend/controllers/inputs.py:183
msgid "DELETE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:212
msgid "FS_WATCHER_DELETION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:213 src/backend/controllers/inputs.py:270
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr ""

#: src/backend/controllers/inputs.py:251 src/backend/controllers/inputs.py:269
msgid "FS_WATCHER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:252
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:275
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:281
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/outputs.py:71 src/backend/controllers/outputs.py:77
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:103
#: src/backend/controllers/outputs.py:109
msgid "UPDATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:135
msgid "CREATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:148
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:161
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:178
#: src/backend/controllers/outputs.py:184
msgid "DELETE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:75
#: src/backend/controllers/positions_masks.py:92
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:137
#: src/backend/controllers/positions_masks.py:143
msgid "DELETE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:170
#: src/backend/controllers/positions_masks.py:176
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:193
#: src/backend/controllers/positions_masks.py:199
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:247
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:272
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:292
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:312
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/privileges.py:36
#: src/backend/controllers/privileges.py:64
msgid "GET_PRIVILEGES_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:53 src/backend/controllers/roles.py:59
#: src/backend/controllers/roles.py:106 src/backend/controllers/roles.py:112
#: src/backend/models/roles.py:70
msgid "UPDATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:84 src/backend/models/roles.py:86
msgid "CREATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:125
msgid "GET_ROLE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:142 src/backend/controllers/roles.py:148
msgid "DELETE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:165 src/backend/controllers/roles.py:171
msgid "DISABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:188 src/backend/controllers/roles.py:194
msgid "ENABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:81
msgid "LOAD_METADATA_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:109
#: src/backend/controllers/verifier.py:81
msgid "AT"
msgstr ""

#: src/backend/controllers/splitter.py:226
msgid "ADD_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:277
#: src/backend/controllers/splitter.py:283
#: src/backend/controllers/verifier.py:486
#: src/backend/controllers/verifier.py:492
#: src/backend/controllers/verifier.py:498
msgid "EXPORT_MAARCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:289
#: src/backend/controllers/verifier.py:510
msgid "MAARCH_WS_INFO_EMPTY"
msgstr ""

#: src/backend/controllers/splitter.py:316
#: src/backend/controllers/splitter.py:557
msgid "EXPORT_PDF_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:333
#: src/backend/controllers/splitter.py:577
#: src/backend/controllers/verifier.py:604
msgid "EXPORT_XML_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:354
msgid "UPDATE_BATCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:369
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:385
msgid "UPDATE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:400
#: src/backend/controllers/splitter.py:421
#: src/backend/controllers/splitter.py:436
#: src/backend/controllers/splitter.py:451
msgid "UPDATE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:465
msgid "CMIS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:648
#: src/backend/controllers/verifier.py:761 src/backend/models/splitter.py:401
#: src/backend/models/verifier.py:145
msgid "GET_TOTALS_ERROR"
msgstr ""

#: src/backend/controllers/status.py:35
msgid "RETRIEVES_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/user.py:31
msgid "CREATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:69 src/backend/models/user.py:115
#: src/backend/models/user.py:135
msgid "GET_USER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/user.py:86
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr ""

#: src/backend/controllers/user.py:130
msgid "UPDATE_PROFILE"
msgstr ""

#: src/backend/controllers/user.py:131
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:136
msgid "UPDATE_USER"
msgstr ""

#: src/backend/controllers/user.py:137
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:164 src/backend/controllers/user.py:170
#: src/backend/models/user.py:173
msgid "UPDATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:187 src/backend/controllers/user.py:193
msgid "DELETE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:210 src/backend/controllers/user.py:216
msgid "DISABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:233 src/backend/controllers/user.py:239
msgid "ENABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:259 src/backend/controllers/user.py:265
#: src/backend/models/user.py:191
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:58 src/backend/models/verifier.py:34
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:175
#: src/backend/controllers/verifier.py:265
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:200
#: src/backend/controllers/verifier.py:285
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:224
#: src/backend/controllers/verifier.py:244
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:302
#: src/backend/controllers/verifier.py:308
msgid "DELETE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:326
#: src/backend/controllers/verifier.py:332
msgid "UPDATE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:352
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:493
msgid "PDF_FILE_NOT_FOUND"
msgstr ""

#: src/backend/controllers/verifier.py:504
msgid "MAARCH_WS_INFO_WRONG"
msgstr ""

#: src/backend/controllers/verifier.py:598
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/verifier.py:683
#: src/backend/controllers/verifier.py:686
#: src/backend/controllers/verifier.py:699
#: src/backend/controllers/verifier.py:717
#: src/backend/controllers/verifier.py:718
msgid "API_INSEE_ERROR_CONNEXION"
msgstr ""

#: src/backend/controllers/verifier.py:741
msgid "VAT_NOT_VALID"
msgstr ""

#: src/backend/controllers/verifier.py:745
#: src/backend/controllers/verifier.py:746
msgid "VAT_API_ERROR"
msgstr ""

#: src/backend/models/accounts.py:90
msgid "SUPPLIER_UPDATE_ERROR"
msgstr ""

#: src/backend/models/auth.py:37 src/backend/models/auth.py:87
#: src/backend/models/user.py:37 src/backend/rest/auth.py:91
msgid "BAD_USERNAME"
msgstr ""

#: src/backend/models/auth.py:39 src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr ""

#: src/backend/models/auth.py:41
msgid "USER_DELETED"
msgstr ""

#: src/backend/models/auth.py:43
msgid "USER_DISABLED"
msgstr ""

#: src/backend/models/auth.py:60 src/backend/models/auth.py:70
#: src/backend/models/roles.py:50
msgid "ROLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/auth.py:117 src/backend/rest/auth.py:222
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr ""

#: src/backend/models/auth.py:138
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/models/auth.py:176
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:194
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/config.py:131
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr ""

#: src/backend/models/config.py:149
msgid "UPDATE_REGEX_ERROR"
msgstr ""

#: src/backend/models/config.py:171
msgid "UPDATE_DOCSERVER_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:48
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:51
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr ""

#: src/backend/models/custom_fields.py:92
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:112
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:45
msgid "ADD_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:48
msgid "DOCTYPE_ALREADY_EXIST"
msgstr ""

#: src/backend/models/doctypes.py:85
msgid "UPDATE_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:112 src/backend/models/doctypes.py:115
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/forms.py:71
msgid "GET_DEFAULT_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:91
msgid "UPDATE_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:109
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/forms.py:157
msgid "ADD_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:160
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/inputs.py:50
msgid "INPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/inputs.py:84
msgid "INPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/inputs.py:100
msgid "INPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:64
msgid "OUTPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:83
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:103
msgid "OUTPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:119
msgid "OUTPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:52
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:72
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:90
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:120
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:123
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/privileges.py:32 src/backend/models/privileges.py:49
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr ""

#: src/backend/models/roles.py:104
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr ""

#: src/backend/models/roles.py:122
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:64
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/splitter.py:103
msgid "UPDATE_SETTINGS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:124
msgid "INSERT_PAGE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:182
msgid "GET_BATCH_ERROR"
msgstr ""

#: src/backend/models/splitter.py:201
msgid "GET_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:220
msgid "GET_PAGES_ERROR"
msgstr ""

#: src/backend/models/splitter.py:238
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:257
msgid "GET_DOCUMENT_ERROR"
msgstr ""

#: src/backend/models/splitter.py:275
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/status.py:34
msgid "NO_STATUS"
msgstr ""

#: src/backend/models/user.py:41
msgid "USER"
msgstr ""

#: src/backend/models/user.py:41
msgid "ALREADY_REGISTERED"
msgstr ""

#: src/backend/models/verifier.py:86 src/backend/models/verifier.py:103
msgid "INVOICE_UPDATE_ERROR"
msgstr ""

#: src/backend/rest/auth.py:47 src/backend/rest/auth.py:95
msgid "PGSQL_ERROR"
msgstr ""

#: src/backend/rest/auth.py:80 src/backend/rest/auth.py:255
#: src/backend/rest/auth.py:269 src/backend/rest/auth.py:278
#: src/backend/rest/auth.py:283 src/backend/rest/auth.py:477
msgid "LDAP_CONNECTION_ERROR"
msgstr ""

#: src/backend/rest/auth.py:81
msgid "LOGIN_LDAP_ERROR"
msgstr ""

#: src/backend/rest/auth.py:203
msgid "AUTH_METHOD_ERROR"
msgstr ""

#: src/backend/rest/auth.py:208
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr ""

#: src/backend/rest/auth.py:221
msgid "LDAP_ERROR"
msgstr ""

#: src/backend/rest/auth.py:253 src/backend/rest/auth.py:267
#: src/backend/rest/auth.py:276
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr ""

#: src/backend/rest/auth.py:287
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr ""

#: src/backend/rest/auth.py:289 src/backend/rest/auth.py:482
#: src/backend/rest/auth.py:488
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr ""

#: src/backend/rest/auth.py:464 src/backend/rest/auth.py:470
#: src/backend/rest/auth.py:476 src/backend/rest/auth.py:481
#: src/backend/rest/auth.py:487
msgid "LDAP_SYNCHRO_ERROR"
msgstr ""

#: src/backend/rest/auth.py:465 src/backend/rest/auth.py:471
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:500 src/backend/rest/auth.py:527
#: src/backend/rest/auth.py:541
msgid "REQUEST_MODIFS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:513
msgid "RETRIEVE_LOGIN_METHODS_ERROR"
msgstr ""

#: src/backend/rest/splitter.py:39 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr ""

